# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [47]:
import pandas as pd

In [48]:
url_1 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv"
url_2 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv"

In [49]:
dataframe_1 = pd.read_csv(r"C:\Users\yanks\Documents\Data Science-Iron hack\lab-dw-data-cleaning-and-formatting\cleaned_data.csv")
display (dataframe_1)

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount,clean_gender,clean_st,clean_vehicle_class
0,QZ44356,Arizona,F,Bachelor,6979.5359,0.0,94.0,0,Personal Auto,Four-Door Car,1131.464935,Female,Arizona,Four-Door Car
1,AI49188,Nevada,F,Bachelor,12887.4317,48767.0,108.0,0,Personal Auto,Two-Door Car,566.472247,Female,Nevada,Two-Door Car
2,WW63253,California,M,Bachelor,7645.8618,0.0,106.0,0,Corporate Auto,SUV,529.881344,Male,California,SUV
3,GA49547,Washington,M,High School or Below,5363.0765,36357.0,68.0,0,Personal Auto,Four-Door Car,17.269323,Male,Washington,Four-Door Car
4,OC83172,Oregon,F,Bachelor,8256.2978,62902.0,69.0,0,Personal Auto,Two-Door Car,159.383042,Female,Oregon,Two-Door Car
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
949,TM65736,Oregon,M,Master,3059.5503,38644.0,78.0,1,Personal Auto,Four-Door Car,361.455219,Male,Oregon,Four-Door Car
950,VJ51327,Cali,F,High School or Below,20314.9976,63209.0,102.0,2,Personal Auto,SUV,207.320041,Female,California,SUV
951,GS98873,Arizona,F,Bachelor,3239.1247,16061.0,88.0,0,Personal Auto,Four-Door Car,633.600000,Female,Arizona,Four-Door Car
952,CW49887,California,F,Master,4626.8011,79487.0,114.0,0,Special Auto,SUV,547.200000,Female,California,SUV
953,MY31220,California,F,College,8997.0402,54230.0,112.0,0,Personal Auto,Two-Door Car,537.600000,Female,California,Two-Door Car

In [50]:
dataframe_2 = pd.read_csv(url_1)
display(dataframe_2)

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Total Claim Amount,Policy Type,Vehicle Class
0,GS98873,Arizona,F,Bachelor,323912.47%,16061,88,1/0/00,633.600000,Personal Auto,Four-Door Car
1,CW49887,California,F,Master,462680.11%,79487,114,1/0/00,547.200000,Special Auto,SUV
2,MY31220,California,F,College,899704.02%,54230,112,1/0/00,537.600000,Personal Auto,Two-Door Car
3,UH35128,Oregon,F,College,2580706.30%,71210,214,1/1/00,1027.200000,Personal Auto,Luxury Car
4,WH52799,Arizona,F,College,380812.21%,94903,94,1/0/00,451.200000,Corporate Auto,Two-Door Car
...,...,...,...,...,...,...,...,...,...,...,...
991,HV85198,Arizona,M,Master,847141.75%,63513,70,1/0/00,185.667213,Personal Auto,Four-Door Car
992,BS91566,Arizona,F,College,543121.91%,58161,68,1/0/00,140.747286,Corporate Auto,Four-Door Car
993,IL40123,Nevada,F,College,568964.41%,83640,70,1/0/00,471.050488,Corporate Auto,Two-Door Car
994,MY32149,California,F,Master,368672.38%,0,96,1/0/00,28.460568,Personal Auto,Two-Door Car
995,SA91515,California,M,Bachelor,399258.39%,0,111,1/0/00,700.349052,Personal Auto,SUV

In [51]:
dataframe_3 = pd.read_csv(url_2)
display(dataframe_3)

,Customer,State,Customer Lifetime Value,Education,Gender,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Total Claim Amount,Vehicle Class
0,SA25987,Washington,3479.137523,High School or Below,M,0,104,0,Personal Auto,499.200000,Two-Door Car
1,TB86706,Arizona,2502.637401,Master,M,0,66,0,Personal Auto,3.468912,Two-Door Car
2,ZL73902,Nevada,3265.156348,Bachelor,F,25820,82,0,Personal Auto,393.600000,Four-Door Car
3,KX23516,California,4455.843406,High School or Below,F,0,121,0,Personal Auto,699.615192,SUV
4,FN77294,California,7704.958480,High School or Below,M,30366,101,2,Personal Auto,484.800000,SUV
...,...,...,...,...,...,...,...,...,...,...,...
7065,LA72316,California,23405.987980,Bachelor,M,71941,73,0,Personal Auto,198.234764,Four-Door Car
7066,PK87824,California,3096.511217,College,F,21604,79,0,Corporate Auto,379.200000,Four-Door Car
7067,TD14365,California,8163.890428,Bachelor,M,0,85,3,Corporate Auto,790.784983,Four-Door Car
7068,UP19263,California,7524.442436,College,M,21941,96,0,Personal Auto,691.200000,Four-Door Car
7069,Y167826,California,2611.836866,College,M,0,77,0,Corporate Auto,369.600000,Two-Door Car

first, i would like to clean dataframes 2 and 3. afterwards, i would concatenate it with dataframe 1 which is my previous cleaned csv file data since they are all having the same column names.

In [52]:
dataframe_3 = dataframe_3.rename(columns = {"State" : "ST"}) # this dataframe had State and needed to be renamed to ST to march the other dataframes.
display(dataframe_3)

,Customer,ST,Customer Lifetime Value,Education,Gender,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Total Claim Amount,Vehicle Class
0,SA25987,Washington,3479.137523,High School or Below,M,0,104,0,Personal Auto,499.200000,Two-Door Car
1,TB86706,Arizona,2502.637401,Master,M,0,66,0,Personal Auto,3.468912,Two-Door Car
2,ZL73902,Nevada,3265.156348,Bachelor,F,25820,82,0,Personal Auto,393.600000,Four-Door Car
3,KX23516,California,4455.843406,High School or Below,F,0,121,0,Personal Auto,699.615192,SUV
4,FN77294,California,7704.958480,High School or Below,M,30366,101,2,Personal Auto,484.800000,SUV
...,...,...,...,...,...,...,...,...,...,...,...
7065,LA72316,California,23405.987980,Bachelor,M,71941,73,0,Personal Auto,198.234764,Four-Door Car
7066,PK87824,California,3096.511217,College,F,21604,79,0,Corporate Auto,379.200000,Four-Door Car
7067,TD14365,California,8163.890428,Bachelor,M,0,85,3,Corporate Auto,790.784983,Four-Door Car
7068,UP19263,California,7524.442436,College,M,21941,96,0,Personal Auto,691.200000,Four-Door Car
7069,Y167826,California,2611.836866,College,M,0,77,0,Corporate Auto,369.600000,Two-Door Car

In [53]:
dataframe_2.columns = dataframe_2.columns.str.strip().str.lower().str.replace(" ", "_")
dataframe_3.columns = dataframe_3.columns.str.strip().str.lower().str.replace(" ", "_")

display(dataframe_2.columns.to_list())
display(dataframe_3.columns.to_list())

['customer',
 'st',
 'gender',
 'education',
 'customer_lifetime_value',
 'income',
 'monthly_premium_auto',
 'number_of_open_complaints',
 'total_claim_amount',
 'policy_type',
 'vehicle_class']

['customer',
 'st',
 'customer_lifetime_value',
 'education',
 'gender',
 'income',
 'monthly_premium_auto',
 'number_of_open_complaints',
 'policy_type',
 'total_claim_amount',
 'vehicle_class']

In [74]:
dataframe_2["number_of_open_complaints"] = dataframe_2["number_of_open_complaints"].str.split("/").str[1]

In [75]:
dataframe_2["number_of_open_complaints"] = pd.to_numeric(dataframe_2["number_of_open_complaints"]).astype("Int64")

In [76]:
dataframe_2_3 = pd.concat([dataframe_2, dataframe_3],axis=0,ignore_index=True) # combining dataframes 2 and 3 by concatenating and ready for further cleaning
display(dataframe_2_3)

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,total_claim_amount,policy_type,vehicle_class
0,GS98873,Arizona,F,Bachelor,323912.47%,16061,88,0,633.600000,Personal Auto,Four-Door Car
1,CW49887,California,F,Master,462680.11%,79487,114,0,547.200000,Special Auto,SUV
2,MY31220,California,F,College,899704.02%,54230,112,0,537.600000,Personal Auto,Two-Door Car
3,UH35128,Oregon,F,College,2580706.30%,71210,214,1,1027.200000,Personal Auto,Luxury Car
4,WH52799,Arizona,F,College,380812.21%,94903,94,0,451.200000,Corporate Auto,Two-Door Car
...,...,...,...,...,...,...,...,...,...,...,...
8061,LA72316,California,M,Bachelor,23405.98798,71941,73,0,198.234764,Personal Auto,Four-Door Car
8062,PK87824,California,F,College,3096.511217,21604,79,0,379.200000,Corporate Auto,Four-Door Car
8063,TD14365,California,M,Bachelor,8163.890428,0,85,3,790.784983,Corporate Auto,Four-Door Car
8064,UP19263,California,M,College,7524.442436,21941,96,0,691.200000,Personal Auto,Four-Door Car
8065,Y167826,California,M,College,2611.836866,0,77,0,369.600000,Corporate Auto,Two-Door Car

In [78]:
dataframe_2_3.dtypes

customer                         str
st                               str
gender                           str
education                        str
customer_lifetime_value       object
income                         int64
monthly_premium_auto           int64
number_of_open_complaints      Int64
total_claim_amount           float64
policy_type                      str
vehicle_class                    str
dtype: object

In [79]:
print("gender")
print(dataframe_2_3["gender"].unique())

print("\nstate")
print(dataframe_2_3["st"].unique())

print("\neducation")
print(dataframe_2_3["education"].unique())

print("\nvehicle class")
print(dataframe_2_3["vehicle_class"].unique())

gender
<ArrowStringArray>
['F', 'M', nan, 'female', 'Male']
Length: 5, dtype: str

state
<ArrowStringArray>
['Arizona', 'California', 'Oregon', 'Nevada', 'Washington', 'AZ']
Length: 6, dtype: str

education
<ArrowStringArray>
['Bachelor', 'Master', 'College', 'Doctor', 'Bachelors',
 'High School or Below']
Length: 6, dtype: str

vehicle class
<ArrowStringArray>
['Four-Door Car',           'SUV',  'Two-Door Car',    'Luxury Car',
    'Sports Car',    'Luxury SUV']
Length: 6, dtype: str

In [80]:
gender_map = {
    "F": "Female", "M": "Male", "female" : "Female", "Male" : "Male" 
}

dataframe_2_3["clean_gender"] = dataframe_2_3["gender"].map(gender_map)
display(dataframe_2_3["clean_gender"].head(100))
print(dataframe_2_3["clean_gender"].unique())

0     Female
1     Female
2     Female
3     Female
4     Female
       ...
95      Male
96      Male
97      Male
98      Male
99    Female
Name: clean_gender, Length: 100, dtype: str

<ArrowStringArray>
['Female', 'Male', nan]
Length: 3, dtype: str

In [81]:
st_map = {
    "Washington" : "Washington", "Arizona" : "Arizona", "Nevada": "Nevada", "California": "California",
    "Oregon" : "Oregon", "AZ" : "Arizona"}

dataframe_2_3["clean_st"]= dataframe_2_3["st"].map(st_map)
display(dataframe_2_3["clean_st"].unique())

<ArrowStringArray>
['Arizona', 'California', 'Oregon', 'Nevada', 'Washington']
Length: 5, dtype: str

In [82]:
dataframe_2_3["education"] = (dataframe_2_3["education"].str.replace("Bachelors", "Bachelor", regex=False)
)
print (dataframe_2_3["education"].unique())

<ArrowStringArray>
['Bachelor', 'Master', 'College', 'Doctor', 'High School or Below']
Length: 5, dtype: str

In [83]:
dataframe_2_3["customer_lifetime_value"] = (dataframe_2_3["customer_lifetime_value"].str.replace("%", "", regex=False))
print(dataframe_2_3["customer_lifetime_value"].head())

0     323912.47
1     462680.11
2     899704.02
3    2580706.30
4     380812.21
Name: customer_lifetime_value, dtype: object

In [84]:
dataframe_2_3["customer_lifetime_value"].dtypes

dtype('O')

In [86]:
dataframe_2_3["customer_lifetime_value"] = pd.to_numeric(dataframe_2_3["customer_lifetime_value"]).astype("float64")

In [88]:
display(dataframe_2_3.isna().sum())
dataframe_2_3.dtypes

customer                        0
st                              0
gender                          5
education                       0
customer_lifetime_value      7074
income                          0
monthly_premium_auto            0
number_of_open_complaints       0
total_claim_amount              0
policy_type                     0
vehicle_class                   0
clean_gender                    5
clean_st                        0
dtype: int64

customer                         str
st                               str
gender                           str
education                        str
customer_lifetime_value      float64
income                         int64
monthly_premium_auto           int64
number_of_open_complaints      Int64
total_claim_amount           float64
policy_type                      str
vehicle_class                    str
clean_gender                     str
clean_st                         str
dtype: object

In [89]:
dataframe_2_3["customer_lifetime_value"] = dataframe_2_3["customer_lifetime_value"]/100 
print(dataframe_2_3["customer_lifetime_value"])

0        3239.1247
1        4626.8011
2        8997.0402
3       25807.0630
4        3808.1221
           ...
8061           NaN
8062           NaN
8063           NaN
8064           NaN
8065           NaN
Name: customer_lifetime_value, Length: 8066, dtype: float64

In [90]:
vehicle_class_map = {
    "Four-Door Car": "Four-Door Car",  "Two-Door Car" : "Two-Door Car", "SUV" : "SUV", "Luxury SUV" : "Luxury",
    "Sports Car" : "Luxury",  "Luxury Car" : "Luxury"
}

dataframe_2_3["clean_vehicle_class"] = dataframe_2_3["vehicle_class"].map(vehicle_class_map)
print(dataframe_2_3["clean_vehicle_class"])
dataframe_2_3["clean_vehicle_class"].unique()

0       Four-Door Car
1                 SUV
2        Two-Door Car
3              Luxury
4        Two-Door Car
            ...
8061    Four-Door Car
8062    Four-Door Car
8063    Four-Door Car
8064    Four-Door Car
8065     Two-Door Car
Name: clean_vehicle_class, Length: 8066, dtype: str

<ArrowStringArray>
['Four-Door Car', 'SUV', 'Two-Door Car', 'Luxury']
Length: 4, dtype: str

In [91]:
dataframe_2_3["number_of_open_complaints"].unique()

<IntegerArray>
[0, 1, 3, 5, 2, 4]
Length: 6, dtype: Int64

In [104]:
display((dataframe_2_3).head(10))

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,total_claim_amount,policy_type,vehicle_class,clean_gender,clean_st,clean_vehicle_class,customer_lifetime_value_filled
0,GS98873,Arizona,F,Bachelor,3239.1247,16061,88,0,633.600000,Personal Auto,Four-Door Car,Female,Arizona,Four-Door Car,3239.1247
1,CW49887,California,F,Master,4626.8011,79487,114,0,547.200000,Special Auto,SUV,Female,California,SUV,4626.8011
2,MY31220,California,F,College,8997.0402,54230,112,0,537.600000,Personal Auto,Two-Door Car,Female,California,Two-Door Car,8997.0402
3,UH35128,Oregon,F,College,25807.0630,71210,214,1,1027.200000,Personal Auto,Luxury Car,Female,Oregon,Luxury,25807.0630
4,WH52799,Arizona,F,College,3808.1221,94903,94,0,451.200000,Corporate Auto,Two-Door Car,Female,Arizona,Two-Door Car,3808.1221
5,WL99637,Arizona,M,Bachelor,7614.1380,27293,96,0,469.030907,Personal Auto,Two-Door Car,Male,Arizona,Two-Door Car,7614.1380
6,UC84059,California,F,Master,6898.4553,70950,171,0,565.929394,Personal Auto,Sports Car,Female,California,Luxury,6898.4553
7,HW62747,Oregon,M,College,2298.3792,0,63,0,302.400000,Corporate Auto,Four-Door Car,Male,Oregon,Four-Door Car,2298.3792
8,BH11344,Oregon,F,Doctor,2806.6961,37009,71,0,145.673348,Corporate Auto,Two-Door Car,Female,Oregon,Two-Door Car,2806.6961
9,TX28465,Nevada,M,College,5206.1182,52629,65,0,136.684141,Personal Auto,Four-Door Car,Male,Nevada,Four-Door Car,5206.1182

filling the missing values under the customer_lifetime_value column with the mean value

In [95]:
customer_lifetime_value_mean = dataframe_2_3["customer_lifetime_value"].mean()
dataframe_2_3["customer_lifetime_value_filled"] = dataframe_2_3["customer_lifetime_value"].fillna(customer_lifetime_value_mean)

In [102]:
clean_gender_mode = dataframe_2_3["clean_gender"].mode()[0]
dataframe_2_3["clean_gender"] = dataframe_2_3["clean_gender"].fillna(clean_gender_mode)

In [103]:
display(dataframe_2_3.isna().sum())

customer                             0
st                                   0
gender                               5
education                            0
customer_lifetime_value           7074
income                               0
monthly_premium_auto                 0
number_of_open_complaints            0
total_claim_amount                   0
policy_type                          0
vehicle_class                        0
clean_gender                         0
clean_st                             0
clean_vehicle_class                  0
customer_lifetime_value_filled       0
dtype: int64

In [106]:
dataframe_1 = dataframe_1.rename(columns={
    "customer_lifetime_value": "customer_lifetime_value_filled"})

print(dataframe_1.columns.tolist())

['customer', 'st', 'gender', 'education', 'customer_lifetime_value_filled', 'income', 'monthly_premium_auto', 'number_of_open_complaints', 'policy_type', 'vehicle_class', 'total_claim_amount', 'clean_gender', 'clean_st', 'clean_vehicle_class']

In [107]:
print(dataframe_1.columns)
dataframe_2_3.columns

Index(['customer', 'st', 'gender', 'education',
       'customer_lifetime_value_filled', 'income', 'monthly_premium_auto',
       'number_of_open_complaints', 'policy_type', 'vehicle_class',
       'total_claim_amount', 'clean_gender', 'clean_st',
       'clean_vehicle_class'],
      dtype='str')

Index(['customer', 'st', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'total_claim_amount', 'policy_type', 'vehicle_class', 'clean_gender',
       'clean_st', 'clean_vehicle_class', 'customer_lifetime_value_filled'],
      dtype='str')

In [ ]:
new_dataframe_1 = dataframe_1.drop(columns =["st", "gender"]) #dropping unnecessary columns such as the ones with missing values
display(new_dataframe_1)

,customer,education,customer_lifetime_value_filled,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount,clean_gender,clean_st,clean_vehicle_class
0,QZ44356,Bachelor,6979.5359,0.0,94.0,0,Personal Auto,Four-Door Car,1131.464935,Female,Arizona,Four-Door Car
1,AI49188,Bachelor,12887.4317,48767.0,108.0,0,Personal Auto,Two-Door Car,566.472247,Female,Nevada,Two-Door Car
2,WW63253,Bachelor,7645.8618,0.0,106.0,0,Corporate Auto,SUV,529.881344,Male,California,SUV
3,GA49547,High School or Below,5363.0765,36357.0,68.0,0,Personal Auto,Four-Door Car,17.269323,Male,Washington,Four-Door Car
4,OC83172,Bachelor,8256.2978,62902.0,69.0,0,Personal Auto,Two-Door Car,159.383042,Female,Oregon,Two-Door Car
...,...,...,...,...,...,...,...,...,...,...,...,...
949,TM65736,Master,3059.5503,38644.0,78.0,1,Personal Auto,Four-Door Car,361.455219,Male,Oregon,Four-Door Car
950,VJ51327,High School or Below,20314.9976,63209.0,102.0,2,Personal Auto,SUV,207.320041,Female,California,SUV
951,GS98873,Bachelor,3239.1247,16061.0,88.0,0,Personal Auto,Four-Door Car,633.600000,Female,Arizona,Four-Door Car
952,CW49887,Master,4626.8011,79487.0,114.0,0,Special Auto,SUV,547.200000,Female,California,SUV
953,MY31220,College,8997.0402,54230.0,112.0,0,Personal Auto,Two-Door Car,537.600000,Female,California,Two-Door Car

In [110]:
new_dataframe_2_3 = dataframe_2_3.drop(columns =["st", "gender", "customer_lifetime_value"])
display(new_dataframe_2_3)

,customer,education,income,monthly_premium_auto,number_of_open_complaints,total_claim_amount,policy_type,vehicle_class,clean_gender,clean_st,clean_vehicle_class,customer_lifetime_value_filled
0,GS98873,Bachelor,16061,88,0,633.600000,Personal Auto,Four-Door Car,Female,Arizona,Four-Door Car,3239.124700
1,CW49887,Master,79487,114,0,547.200000,Special Auto,SUV,Female,California,SUV,4626.801100
2,MY31220,College,54230,112,0,537.600000,Personal Auto,Two-Door Car,Female,California,Two-Door Car,8997.040200
3,UH35128,College,71210,214,1,1027.200000,Personal Auto,Luxury Car,Female,Oregon,Luxury,25807.063000
4,WH52799,College,94903,94,0,451.200000,Corporate Auto,Two-Door Car,Female,Arizona,Two-Door Car,3808.122100
...,...,...,...,...,...,...,...,...,...,...,...,...
8061,LA72316,Bachelor,71941,73,0,198.234764,Personal Auto,Four-Door Car,Male,California,Four-Door Car,7651.493931
8062,PK87824,College,21604,79,0,379.200000,Corporate Auto,Four-Door Car,Female,California,Four-Door Car,7651.493931
8063,TD14365,Bachelor,0,85,3,790.784983,Corporate Auto,Four-Door Car,Male,California,Four-Door Car,7651.493931
8064,UP19263,College,21941,96,0,691.200000,Personal Auto,Four-Door Car,Male,California,Four-Door Car,7651.493931
8065,Y167826,College,0,77,0,369.600000,Corporate Auto,Two-Door Car,Male,California,Two-Door Car,7651.493931

In [113]:
print(new_dataframe_1.isna().sum())
print("\n")
print(new_dataframe_2_3.isna().sum())

customer                          0
education                         0
customer_lifetime_value_filled    0
income                            0
monthly_premium_auto              0
number_of_open_complaints         0
policy_type                       0
vehicle_class                     0
total_claim_amount                0
clean_gender                      0
clean_st                          0
clean_vehicle_class               0
dtype: int64


customer                          0
education                         0
income                            0
monthly_premium_auto              0
number_of_open_complaints         0
total_claim_amount                0
policy_type                       0
vehicle_class                     0
clean_gender                      0
clean_st                          0
clean_vehicle_class               0
customer_lifetime_value_filled    0
dtype: int64

In [ ]:
cleaned_dataframe = pd.concat([new_dataframe_1, new_dataframe_2_3],axis=0,ignore_index=True) #combining all the dataframes together using concat since they share the same column names
display(cleaned_dataframe)

,customer,education,customer_lifetime_value_filled,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount,clean_gender,clean_st,clean_vehicle_class
0,QZ44356,Bachelor,6979.535900,0.0,94.0,0,Personal Auto,Four-Door Car,1131.464935,Female,Arizona,Four-Door Car
1,AI49188,Bachelor,12887.431700,48767.0,108.0,0,Personal Auto,Two-Door Car,566.472247,Female,Nevada,Two-Door Car
2,WW63253,Bachelor,7645.861800,0.0,106.0,0,Corporate Auto,SUV,529.881344,Male,California,SUV
3,GA49547,High School or Below,5363.076500,36357.0,68.0,0,Personal Auto,Four-Door Car,17.269323,Male,Washington,Four-Door Car
4,OC83172,Bachelor,8256.297800,62902.0,69.0,0,Personal Auto,Two-Door Car,159.383042,Female,Oregon,Two-Door Car
...,...,...,...,...,...,...,...,...,...,...,...,...
9015,LA72316,Bachelor,7651.493931,71941.0,73.0,0,Personal Auto,Four-Door Car,198.234764,Male,California,Four-Door Car
9016,PK87824,College,7651.493931,21604.0,79.0,0,Corporate Auto,Four-Door Car,379.200000,Female,California,Four-Door Car
9017,TD14365,Bachelor,7651.493931,0.0,85.0,3,Corporate Auto,Four-Door Car,790.784983,Male,California,Four-Door Car
9018,UP19263,College,7651.493931,21941.0,96.0,0,Personal Auto,Four-Door Car,691.200000,Male,California,Four-Door Car
9019,Y167826,College,7651.493931,0.0,77.0,0,Corporate Auto,Two-Door Car,369.600000,Male,California,Two-Door Car

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [117]:
import pandas as dp

In [118]:
link = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv"

In [119]:
df = dp.read_csv(link)
display (df)

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10905,10905,FE99816,Nevada,15563.369440,No,Premium,Bachelor,2011-01-19,Unemployed,F,...,7,Personal Auto,Personal L1,Offer3,Web,1214.400000,Luxury Car,Medsize,A,1
10906,10906,KX53892,Oregon,5259.444853,No,Basic,College,2011-01-06,Employed,F,...,6,Personal Auto,Personal L3,Offer2,Branch,273.018929,Four-Door Car,Medsize,A,1
10907,10907,TL39050,Arizona,23893.304100,No,Extended,Bachelor,2011-02-06,Employed,F,...,2,Corporate Auto,Corporate L3,Offer1,Web,381.306996,Luxury SUV,Medsize,A,2
10908,10908,WA60547,California,11971.977650,No,Premium,College,2011-02-13,Employed,F,...,6,Personal Auto,Personal L1,Offer1,Branch,618.288849,SUV,Medsize,A,2
10909,10909,IV32877,California,6857.519928,No,Basic,Bachelor,2011-01-08,Unemployed,M,...,3,Personal Auto,Personal L1,Offer4,Web,1021.719397,SUV,Medsize,A,1

In [120]:
df.isna().sum()

unnamed:_0                       0
customer                         0
state                            0
customer_lifetime_value          0
response                         0
coverage                         0
education                        0
effective_to_date                0
employmentstatus                 0
gender                           0
income                           0
location_code                    0
marital_status                   0
monthly_premium_auto             0
months_since_last_claim          0
months_since_policy_inception    0
number_of_open_complaints        0
number_of_policies               0
policy_type                      0
policy                           0
renew_offer_type                 0
sales_channel                    0
total_claim_amount               0
vehicle_class                    0
vehicle_size                     0
vehicle_type                     0
month                            0
dtype: int64

In [124]:
df.dtypes

unnamed:_0                         int64
customer                             str
state                                str
customer_lifetime_value          float64
response                             str
coverage                             str
education                            str
effective_to_date                    str
employmentstatus                     str
gender                               str
income                             int64
location_code                        str
marital_status                       str
monthly_premium_auto               int64
months_since_last_claim          float64
months_since_policy_inception      int64
number_of_open_complaints        float64
number_of_policies                 int64
policy_type                          str
policy                               str
renew_offer_type                     str
sales_channel                        str
total_claim_amount               float64
vehicle_class                        str
vehicle_size                         str
vehicle_type                         str
month                              int64
dtype: object

In [127]:
df["customer_lifetime_value"].sum()

np.float64(87479010.33252001)

In [128]:
df["total_claim_amount"].sum()

np.float64(4744631.677058)

In [125]:
df["income"]

0        48029
1            0
2        22139
3        49078
4        23675
         ...
10905        0
10906    61146
10907    39837
10908    64195
10909        0
Name: income, Length: 10910, dtype: int64

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

In [ ]:
revenue_summary = df.pivot_table(
    index="sales_channel",
    values="customer_lifetime_value",
    aggfunc="sum"
)

revenue_summary_decimal = revenue_summary.round(2)
display(revenue_summary_decimal)   # reason for using the customer lifetime value as the value is that it is what the company has estimated to gain from the customers over their contract or relationship as long as they patronise their insurance which is also higher than the claims

               customer_lifetime_value
sales_channel
Agent                      33057887.85
Branch                     24359201.21
Call Center                17364288.37
Web                        12697632.90

In [ ]:
sum_by_lifetime = (
    df
    .groupby("sales_channel")["customer_lifetime_value"]
    .sum()
    .round(2)
)

display(sum_by_lifetime)  #     I again realised that i could use the groupby method to also get the same results.

sales_channel
Agent          33057887.85
Branch         24359201.21
Call Center    17364288.37
Web            12697632.90
Name: customer_lifetime_value, dtype: float64

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

In [137]:
average_customer_lifetime = df.pivot_table(
    index="gender",
    columns="education",
    values="customer_lifetime_value",
    aggfunc="mean"
)
display (average_customer_lifetime)

education,Bachelor,College,Doctor,High School or Below,Master
gender,,,,,
F,7874.269478,7748.823325,7328.508916,8675.220201,8157.053154
M,7703.601675,8052.459288,7415.333638,8149.687783,8168.832659

In [138]:
average_by_lifetime = (
    df
    .groupby(["gender", "education"])["customer_lifetime_value"]
    .mean()
)

display(average_customer_lifetime)

education,Bachelor,College,Doctor,High School or Below,Master
gender,,,,,
F,7874.269478,7748.823325,7328.508916,8675.220201,8157.053154
M,7703.601675,8052.459288,7415.333638,8149.687783,8168.832659

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [139]:
df["month"]

0        2
1        1
2        2
3        1
4        1
        ..
10905    1
10906    1
10907    2
10908    2
10909    1
Name: month, Length: 10910, dtype: int64

In [142]:
df["number_of_open_complaints"] = df["number_of_open_complaints"].astype(int)

In [143]:
sum_number_of_complaints = df.pivot_table(
    index="month",
    columns="policy_type",
    values="number_of_open_complaints",
    aggfunc="sum"
)
display (sum_number_of_complaints)

policy_type  Corporate Auto  Personal Auto  Special Auto
month
1                       415           1635            84
2                       361           1363            91

In [146]:
sum_number_of_complaints = sum_number_of_complaints.reset_index()
display(sum_number_of_complaints)

policy_type  index  month  Corporate Auto  Personal Auto  Special Auto
0                0      1             415           1635            84
1                1      2             361           1363            91

In [147]:
sum_number_of_complaints = sum_number_of_complaints.drop(columns=["index"])
display (sum_number_of_complaints)

policy_type  month  Corporate Auto  Personal Auto  Special Auto
0                1             415           1635            84
1                2             361           1363            91

In [148]:
number_complaints = pd.melt(
    sum_number_of_complaints,
    id_vars=["month"],
    value_vars=["Corporate Auto", "Personal Auto", "Special Auto"],
    var_name="Auto Policy",
    value_name="sum_of_complaints"
)
display(number_complaints)

   month     Auto Policy  sum_of_complaints
0      1  Corporate Auto                415
1      2  Corporate Auto                361
2      1   Personal Auto               1635
3      2   Personal Auto               1363
4      1    Special Auto                 84
5      2    Special Auto                 91